__title__ = "audio_preprocess"
__description__ = "Audio preprocessing library for deepfake audio detection"
__url__ = ""
__version__ = "0.2.0"
__author__ = "Thien-Phuc Doan"
__author_email__ = "josebeo2016@gmail.com"
__license__ = "MIT"
